CREATE TABLE BOARD(

BOARD_NUM NUMBER,

BOARD_WRITER VARCHAR2(20) NOT NULL,

BOARD_TITLE VARCHAR2(50) NOT NULL,

BOARD_CONTENT VARCHAR2(2000) NOT NULL,

BOARD_DATE DATE DEFAULT SYSDATE,

CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_NUM),

CONSTRAINT FK_BOARD_WRITER FOREIGN KEY (BOARD_WRITER) REFERENCES MEMBER (USERID) ON DELETE SET NULL

);

COMMENT ON COLUMN BOARD.BOARD_NUM IS '게시글번호';

COMMENT ON COLUMN BOARD.BOARD_WRITER IS '작성자아이디';

COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';

COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글내용';

COMMENT ON COLUMN BOARD.BOARD_DATE IS '작성날짜';