

CREATE TABLE BOARD (
    NO NUMBER CONSTRAINT PK_BOARD PRIMARY KEY,
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(500) NOT NULL,
    WRITER VARCHAR2(30),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK ( STATUS IN ('Y', 'N') ),
    CREATE_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_WRITER FOREIGN KEY ( WRITER )
        REFERENCES MEMBER ( ID )
);
    