-- MySQL Script generated by MySQL Workbench
-- 07/28/21 20:03:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema2
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`부서`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`부서` (
  `부서번호` CHAR(4) NOT NULL,
  `부서이름` VARCHAR(45) NULL,
  `전화번호` CHAR(13) NULL,
  `소재지` VARCHAR(100) NULL,
  `관리자번호` CHAR(9) NULL,
  PRIMARY KEY (`부서번호`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`사원`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`사원` (
  `사원번호` CHAR(9) NOT NULL,
  `사원이름` CHAR(10) NULL,
  `전화번호` CHAR(13) NULL,
  `주소` VARCHAR(200) NULL,
  `생년월일` DATE NULL,
  `성별` ENUM('남', '여') NULL,
  `부서_부서번호` CHAR(4) NOT NULL,
  PRIMARY KEY (`사원번호`),
  INDEX `fk_사원_부서1_idx` (`부서_부서번호` ASC),
  CONSTRAINT `fk_사원_부서1`
    FOREIGN KEY (`부서_부서번호`)
    REFERENCES `mydb`.`부서` (`부서번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`부가정보`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`부가정보` (
  `신장` INT NOT NULL,
  `체중` FLOAT NULL,
  `혈액형` ENUM('a', 'b', 'ab', 'o') NULL,
  `종교` VARCHAR(30) NULL,
  `사원_사원번호` CHAR(9) NOT NULL,
  PRIMARY KEY (`신장`, `사원_사원번호`),
  INDEX `fk_부가정보_사원_idx` (`사원_사원번호` ASC),
  CONSTRAINT `fk_부가정보_사원`
    FOREIGN KEY (`사원_사원번호`)
    REFERENCES `mydb`.`사원` (`사원번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`프로젝트`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`프로젝트` (
  `프로젝트번호` CHAR(10) NOT NULL,
  `프로젝트명` VARCHAR(100) NULL,
  `시작일자` DATETIME NULL,
  `종료일자` DATETIME NULL,
  PRIMARY KEY (`프로젝트번호`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`참여내역`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`참여내역` (
  `프로젝트번호` CHAR(10) NOT NULL,
  `사원번호` CHAR(9) NULL,
  `참여시작일` DATE NULL,
  `참여종료일` DATE NULL,
  PRIMARY KEY (`프로젝트번호`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`부양가족`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`부양가족` (
  `가족이름` CHAR(10) NOT NULL,
  `성별` ENUM('남', '여') NULL,
  `생년월일` DATE NULL,
  `관계` VARCHAR(45) NULL,
  `사원_사원번호` CHAR(9) NOT NULL,
  PRIMARY KEY (`가족이름`, `사원_사원번호`),
  INDEX `fk_부양가족_사원1_idx` (`사원_사원번호` ASC),
  CONSTRAINT `fk_부양가족_사원1`
    FOREIGN KEY (`사원_사원번호`)
    REFERENCES `mydb`.`사원` (`사원번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
